pipeline:
  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: lidarr-dev

  test:
    image: spritsail/docker-test
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: lidarr-dev
    run_args: -t -e SUID=0 -e API_KEY=drone
    curl: ':8686/api/v1/system/status'
    curl_opts: --header x-api-key:drone
    verbose: true
    pipe: |
      jq -r ".version" |
      grep -qw "$(label io.spritsail.version.lidarr)"

  publish:
    image: spritsail/docker-publish
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password ]
    when: { branch: [ master ], event: [ push, tag, deployment ] }
    from: lidarr-dev
    repo: spritsail/lidarr
    tags:
      - 'latest'
      - '%label io.spritsail.version.lidarr | %auto'

  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]
