---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: lidarr-dev

- name: test
  pull: always
  image: spritsail/docker-test
  settings:
    repo: lidarr-dev
    run_args: -t -e SUID=0 -e API_KEY=drone
    curl: ':8686/api/v1/system/status'
    curl_opts: --header x-api-key:drone
    pipe: |
      jq -r ".version" |
      grep -qw "$(label io.spritsail.version.lidarr)"

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: lidarr-dev
    repo: spritsail/lidarr
    tags:
    - latest
    - "%label io.spritsail.version.lidarr | %auto"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - push

...
